import { useEffect, useState } from 'react';
import { request } from '../../api/client';

type Settings = { pr_comments_enabled: boolean; pr_comment_min_confidence: number; pr_comment_allowed_branches: string; pr_comment_include_similar_incident: boolean; pr_comment_include_patch: boolean };
const defaults: Settings = { pr_comments_enabled: false, pr_comment_min_confidence: 0.8, pr_comment_allowed_branches: 'main', pr_comment_include_similar_incident: true, pr_comment_include_patch: false };

export function PRCommentSettings({ repositoryId, role }: { repositoryId: string; role: string }) {
  const [value, setValue] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const editable = role === 'OWNER' || role === 'ADMIN';
  useEffect(() => { request(`/repositories/${repositoryId}/pr-comment-settings`).then(setValue).catch(() => setMessage('Could not load PR comment settings.')).finally(() => setLoading(false)); }, [repositoryId]);
  const save = async () => { const branches = value.pr_comment_allowed_branches.split(',').map(branch => branch.trim()).filter(Boolean); if (!branches.length) { setMessage('Enter at least one allowed branch.'); return; } if (value.pr_comment_min_confidence < 0 || value.pr_comment_min_confidence > 1) { setMessage('Confidence must be between 0% and 100%.'); return; } setSaving(true); setMessage(''); try { await request(`/repositories/${repositoryId}/pr-comment-settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...value, pr_comment_allowed_branches: branches.join(',') }) }); setMessage('PR comment settings saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save settings.'); } finally { setSaving(false); } };
  if (loading) return <div className="panel empty">Loading PR comment settings...</div>;
  return <div className="panel form-panel"><div className="detail-head"><div><p className="kicker">REPOSITORY AUTOMATION</p><h3>Pull-request comments</h3></div><span className="tag">{editable ? 'Editable' : 'Read only'}</span></div>{message && <div className="notice" role="alert">{message}</div>}<label className="toggle-row"><input type="checkbox" checked={value.pr_comments_enabled} disabled={!editable} onChange={event => setValue({ ...value, pr_comments_enabled: event.target.checked })}/>Enable PR comments</label><label>Minimum confidence ({Math.round(value.pr_comment_min_confidence * 100)}%)<input type="number" min="0" max="100" value={Math.round(value.pr_comment_min_confidence * 100)} disabled={!editable} onChange={event => setValue({ ...value, pr_comment_min_confidence: Number(event.target.value) / 100 })}/></label><label>Allowed branches<input value={value.pr_comment_allowed_branches} disabled={!editable} onChange={event => setValue({ ...value, pr_comment_allowed_branches: event.target.value })}/></label><label className="toggle-row"><input type="checkbox" checked={value.pr_comment_include_similar_incident} disabled={!editable} onChange={event => setValue({ ...value, pr_comment_include_similar_incident: event.target.checked })}/>Include similar resolved incident</label><label className="toggle-row"><input type="checkbox" checked={value.pr_comment_include_patch} disabled={true}/>Include suggested patch <small>Unavailable until safe patch suggestions are implemented.</small></label>{editable && <button className="primary" disabled={saving} onClick={save}>{saving ? 'Saving...' : 'Save PR comment settings'}</button>}</div>;
}
