apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pipelinemedic
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pipelinemedic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pipelinemedic-backend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pipelinemedic-config
                  key: DATABASE_URL
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: pipelinemedic-config
                  key: FRONTEND_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: pipelinemedic-config
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pipelinemedic-secret
                  key: JWT_SECRET
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: pipelinemedic-secret
                  key: GITHUB_WEBHOOK_SECRET
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pipelinemedic-secret
                  key: GITHUB_TOKEN
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pipelinemedic-secret
                  key: GROQ_API_KEY
          envFrom:
            - configMapRef:
                name: pipelinemedic-config
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
