apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipelinemedic
  namespace: pipelinemedic
spec:
  rules:
    - host: pipelinemedic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
