apiVersion: v1
kind: Secret
metadata:
  name: pipelinemedic-secret
  namespace: pipelinemedic
type: Opaque
stringData:
  JWT_SECRET: "replace-with-a-long-random-secret"
  GITHUB_WEBHOOK_SECRET: "replace-me"
  GITHUB_TOKEN: "replace-me"
  GROQ_API_KEY: "replace-me"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
